name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Elm
        uses: hrzhuang/install-elm@v1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create public directory
        run: mkdir public
      - name: Copy textures into public
        run: cp -r textures public
      - name: Build Elm code
        run: elm make --optimize --output public/index.html src/Main.elm
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
